iso_codes = {
    "China": "CN",
    "Italy": "IT",
    "Iran": "IR",
    "S. Korea": "KR",
    "Spain": "ES",
    "Germany": "DE",
    "France": "FR",
    "USA": "US",
    "Switzerland": "CH",
    "UK": "GB",
    "Norway": "NO",
    "Sweden": "SE",
    "Netherlands": "NL",
    "Denmark": "DK",
    "Japan": "JP",
    "Diamond Princess": "DP",
    "Belgium": "BE",
    "Austria": "AT",
    "Qatar": "QA",
    "Australia": "AU",
    "Canada": "CA",
    "Malaysia": "MY",
    "Greece": "GR",
    "Finland": "FI",
    "Bahrain": "BH",
    "Singapore": "SG",
    "Israel": "IL",
    "Czechia": "CZ",
    "Slovenia": "SI",
    "Portugal": "PT",
    "Iceland": "IS",
    "Brazil": "BR",
    "Hong Kong": "HK",
    "Ireland": "IE",
    "Romania": "RO",
    "Estonia": "EE",
    "Philippines": "PH",
    "Iraq": "IQ",
    "Egypt": "EG",
    "Kuwait": "KW",
    "Poland": "PL",
    "Saudi Arabia": "SA",
    "San Marino": "SM",
    "India": "IN",
    "Indonesia": "ID",
    "Lebanon": "LB",
    "UAE": "AE",
    "Thailand": "TH",
    "Chile": "CL",
    "Russia": "RS",
    "Taiwan": "TW",
    "Vietnam": "VN",
    "Luxembourg": "LU",
    "Serbia": "RS",
    "Argentina": "AR",
    "Slovakia": "SK",
    "Bulgaria": "BG",
    "Brunei": "BN",
    "Croatia": "HR",
    "Albania": "AL",
    "Peru": "PE",
    "South Africa": "ZA",
    "Palestine": "PS",
    "Algeria": "DZ",
    "Panama": "PA",
    "Pakistan": "PK",
    "Georgia": "GE",
    "Hungary": "HU",
    "Equatorial Guinea": "GQ",
    "Ecuador": "EC",
    "Belarus": "BY",
    "Costa Rica": "CR",
    "Latvia": "LV",
    "Mexico": "MX",
    "Cyprus": "CY",
    "Colombia": "CO",
    "Senegal": "SN",
    "Bosnia and Herzegovina": "BA",
    "Oman": "OM",
    "Morocco": "MA",
    "Armenia": "AM",
    "Tunisia": "TN",
    "Malta": "MT",
    "Azerbaijan": "AZ",
    "North Macedonia": "MK",
    "Moldova": "MD",
    "Afghanistan": "AF",
    "Dominican Republic": "DO",
    "Macao": "MO",
    "Sri Lanka": "LK",
    "Bolivia": "BO",
    "Maldives": "MV",
    "Martinique": "MQ",
    "Lithuania": "LT",
    "Faeroe Islands": "FO",
    "Jamaica": "JM",
    "Cambodia": "KH",
    "New Zealand": "NZ",
    "French Guiana": "GF",
    "Paraguay": "PY",
    "Kazakhstan": "KZ",
    "Reunion": "RE",
    "Turkey": "TR",
    "Bangladesh": "BD",
    "Cuba": "CU",
    "Liechtenstein": "LI",
    "Uruguay": "UY",
    "Ukraine": "UA",
    "Channel Islands": "KY",
    "French Polynesia": "PF",
    "Guadeloupe": "GP",
    "Honduras": "HN",
    "Puerto Rico": "PR",
    "Monaco": "MC",
    "Nigeria": "NG",
    "Aruba": "AW",
    "Burkina Faso": "BF",
    "Cameroon": "CM",
    "Ivory Coast": "CI",
    "Curacao": "CW",
    "DRC": "CD",
    "Ghana": "GH",
    "Namibia": "NA",
    "Saint Martin": "MF",
    "Seychelles": "SC",
    "Trinidad and Tobago": "TT",
    "Venezuela": "VE",
    "Guyana": "GY",
    "Sudan": "SD",
    "Andorra": "AD",
    "Jordan": "JO",
    "Nepal": "NP",
    "Antigua and Barbuda": "AG",
    "Bhutan": "BT",
    "Cayman Islands": "KY",
    "Ethiopia": "ET",
    "Gabon": "GA",
    "Gibraltar": "GI",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Vatican City": "VA",
    "Kenya": "KE",
    "Mauritania": "MR",
    "Mayotte": "YT",
    "Mongolia": "MN",
    "Rwanda": "RW",
    "St. Barth": "BL",
    "Saint Lucia": "LC",
    "St. Vincent Grenadines": "VC",
    "Suriname": "SR",
    "Eswatini": "SZ",
    "Togo": "TG",
    "U.S. Virgin Islands": "VI"
}